---

- name: Install Resilio Sync
  ansible.builtin.command: "qpkg_cli --keep --manually {{ resilio_download.dest }}"
  register: install_result
  become: true
  changed_when: true

- name: Show Resilio Sync install result
  ansible.builtin.debug:
    msg: "{{ install_result.stdout_lines }}"

- name: Wait 30 seconds for installation
  ansible.builtin.pause:
    seconds: 30

- name: Check installation completed
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      qpkg_cli --list | grep '\[ResilioSync\]'
    executable: /bin/bash
  register: list_result
  failed_when: list_result.rc == 0
  retries: 15
  delay: 30
  changed_when: true

- name: Confirm Resilio Sync installed
  ansible.builtin.debug:
    msg: "ResilioSync was installed"
